image: php:7.1

cache:
  paths:
  - vendor/

services:
- mysql:latest

variables:
  MYSQL_DATABASE: testing
  MYSQL_USER: root
  MYSQL_ROOT_PASSWORD: testing

phpunit:
  before_script:
    - apt-get update -yqq
    - apt-get install zip unzip git libjpeg-dev libpng-dev libfreetype6-dev -yqq
    - docker-php-ext-install gd pdo_mysql
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --no-progress --no-interaction --optimize-autoloader
    - cp .env.gitlab .env.testing
  script:
    - php artisan migrate
    - vendor/bin/phpunit

php-cs-fixer:
  before_script:
    - apt-get update -yqq
    - apt-get install git -yqq
    - apt-get install zip unzip
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --no-progress --no-interaction --optimize-autoloader
  script:
    - vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --dry-run --diff
