language: php

php:
  - '7.2'
  - '7.3'

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules

before_script:
  - yarn install && yarn production
  - sudo mysql -e 'CREATE DATABASE homestead;'
  - composer install --no-progress --no-interaction --prefer-dist --no-suggest
  - cp .env.travis .env.testing

script:
  - vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --dry-run --diff
  - vendor/bin/phpunit --testdox

notifications:
  email: false
