version: '3'

services:
  blog-server:
    build: ./provisioning
    image: laravel-blog
    depends_on:
      - mysql
      - mysql-test
      - redis
    volumes:
      - ./:/application:cached

  queue-server:
    build: ./provisioning
    image: laravel-blog
    command: php artisan queue:work
    depends_on:
      - mysql
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel-blog
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  mysql-test:
    image: mysql
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=testing
    volumes:
      - ./storage/tmp/test:/var/lib/mysql:cached

  nginx:
    image: nginx
    ports:
      - '8000:8000'
    volumes:
      - ./provisioning/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./public:/application/public:cached
    depends_on:
      - blog-server

  redis:
    image: redis
    ports:
      - '6379:6379'

  echo-server:
    image: node
    ports:
      - 8888:8888
    working_dir: /application
    volumes:
      - .:/application:cached
    depends_on:
      - redis
      - blog-server
    command: 'npm start'
